Projects:
    Name:
        - yusukefurukawa 
    SubName:
        - test
    Version:
        - 0.0.6
Tests:
    From:
        - 'python:latest'
    Run: 
        >
        ADD requirements.txt .\n
        ADD app.py .\n
        ADD app_test.py .\n
        RUN pip install -r requirements.txt\n
    Phase:
        - tests
    Volume:
        - volume1
    RUN_COMMAND: 
        - 'python app_test.py'
Build:
    From:
        - 'python:latest'
    Run:
        >
        ADD requirements.txt .\n
        ADD app.py .\n
        ADD app_test.py .\n
        RUN pip install -r requirements.txt\n
        CMD ["python", "app.py"]\n
    Phase:
        - build
    Volume:
        - null
    ToMarathon:
        - to_marathon.json
    ENV:
        ENV1:
            - hoge1
        ENV2:
            - hoge2
        DJANGO_SETTINGS_MODULE:
            - little.setting
    ARGS: 
        - '["python", "app.py"]'

Deploy:
    Ignore:
        -- true
Source:
    - getting-started-python
